### ISSUE TITLE
Modify readDatastoreTables function to return values in same units as saved in

### ISSUE THREAD

**Issue by dflynn-volpe** [VisionEval/VisionEval-Dev#18]
Originally created by @gregorbj in April 2018:

When datasets are set in the datastore, units are converted to the default units of the datastore. This is the intended behavior and works fine during model runs because the framework converts units to whatever is specified in module specifications. However, confusion can be caused when using the readDatastoreTables function to query the datastore and check values or compute performance measures because the datasets that are returned are in the units stored in the datastore rather than in the units output from the module. So for example, GHG emissions rates are output in grams per mile but are stored in the datastore in kilograms per mile because the default units for mass are kilograms. The attributes of the returned dataset are consistent with how the dataset is stored so there is no confusion there. In the example, the UNITS attribute of the GHG emissions rate dataset is KG/MI so it is consistent with the data that is returned. However, if the user is expecting GM/MI and is not aware that KG/MI is being returned, they will be confused.

The first thing that should be done is to modify readDatastoreTables to return the UNITS attributes for the datasets so that users are adequately informed.

The second thing that should be done is to modify readDatastoreTables to enable a user to specify the UNITS they want for the dataset that is returned.

**Comment by jrawbits** [comment]
The current VEModel extract function will use an optional display_units.csv file to define desired unit conversions on a field-by-field basis. I'll be looking back at the VEModel reimplementation of readDatastoreTables (or really, the query functions that use readDatastoreTables) to see if the UNITS specified in the query specifications are being used for data conversion (i.e. this bug might have been fixed). If not, it will be trivial to borrow the conversion code used in extracting Datastore fields and apply that. I'll add this to the near term framework development list since all the resources needed to fix it are available.

**Comment by jrawbits** [comment]
This is a really old issue. Suggest that we review the query specification strategy in VE framework 3.0 (VEModel). Some of this issue may already have been fixed: The items used in a query spec are given units to use in the computation, and the resulting measure also has a Units field - those should be explicitly tied to the model's units.csv and framework known units and conversions performed when the query is returned.

**Comment by jrawbits** [comment]
Verify (and fix further or close) with the R 4.2.2 release.

**Comment by jrawbits** [comment]
The current extract and query functions can do unit conversions, with the development-next push 2023-03-24
