### ISSUE TITLE
initialize test for consistent acres-dwelling units

### ISSUE THREAD

**Issue by dflynn-volpe** [VisionEval/VisionEval-Dev#23]
Originally created by @mrspeel December 2018:

One error that would be helpful to catch before runtime is noted below. Can this be added to an initialize module?

Ensure that if dwelling units >0 (VESimHouseholds/bzone_dwelling_units.csv),
unprotected acres (VELandUse/bzone_unprotected_area.csv)>0
by Bzone.

Comment by @gregorbj:

Some changes to the framework software are needed to catch input errors like this. When the framework software loads inputs it only checks the values of the input files. Before adding the Initialize module capability, values could only be checked within individual input fields. Adding Initialize module capabilities added the ability to check between fields. In all cases, input file checks are not made against data that is in the datastore. Therefore, at most, you can only check between input files that are specified by modules within one package. You can't check consistency of inputs between packages (e.g. between VESimHouseholds and VELandUse). This could get even more limiting if we address another issue that has been raised because we can currently only have 1 Initialize module per package. This gets in the way of having different cross-field data checks for different models (RSPM & RPAT) that include modules in the same package. I think that in order to make checks between packages, the framework code will need to be changed to enable pulling data from the datastore so you can get the values that were input by modules in other packages. I don't think this is a trivial thing to do, but then again, it might not be as hard as I worry it would be.

Comment by @gregorbj:

After experimenting with pulling data from the datastore (i.e. enabling Get specification for Initialize modules) I conclude that this can't be done without dropping the goal of checking all inputs at the beginning of a model run, and without changing how model runs are managed by the framework. It is a design goal that all model inputs are checked and added to the datastore at the beginning of a model run so that errors in input data are caught and identified at the beginning rather than in the middle of the model run. Since inputs are processed at the beginning, the data that you might want to pull from the datastore to check against would probably not be there because it would be generated when a module is run.

The specific issue could be dealt with because both dwelling units and unprotected acres are inputs to modules in the VELandUse package. Therefore it would be possible to have an initialize module that will check this.

**Comment by jrawbits** [comment]
This discussion amplifies on considerations in #20 and they should be addressed together.

I'm thinking the role of the initialize function is to vet the input files and decide which make it into the Datastore and what sorts of cross-file consistency needs to be established. So we would run that after all the input files have been added and probably have no issue retrieving from the datastore (though framework support that is different from how the modules get their data would be needed).

**Comment by jrawbits** [comment]
A fix for this issue is forthcoming in the R 4.2.2 release. In particular, an optional function can be constructed for any module called <ModuleName>ValidateInputFile. If it exists, it will be called for each input file specified for the module and the input file rows will be checked for consistency. On the particular errors listed, the two files are checked separately. But note that zero-household zones (no dwelling units) seems to create a cascade of terrible problems, so we declare that an error, and it is also an error to have zero developable land.

We could refine that if it turns out that it is the intersection of these two zeroes that is the problem: I just need to verify that the CSV files are checked and fully loaded into the datastore one at a time - then we could also check incoming data against stuff previously loaded (need to be careful about maintaining order independence).

I'd like to move away from the Initialize magic module architecture since it commingles modules and packages in a bad way. Each module should have its own initialize/validation function, and they should be called at such a time that other required fields will be present in the datastore (or submitted from different input files to the same module). First swipe at the validation coming up; we'll revisit during the next architecture update.
