### ISSUE TITLE
Model fails in 'AssignLocTypes' module

### ISSUE THREAD

**Issue by dsrosenthal5** [VisionEval/VisionEval-Dev#38]
My data is passing the initialize test but the model is crashing in the 'AssignLocTypes' module with an out of bounds error.
![image](https://user-images.githubusercontent.com/48492597/57485310-3d287800-7260-11e9-8378-e0a3fac9cf9e.png)
I'm thinking the issue traces all the way back to the CreateHouseholds module but I have not been able to resolve the problem.

**Comment by dflynn-volpe** [comment]
@dsrosenthal5 This issue was also encountered by @shichenfan. Can you look at what you have in `bzone_urban-town_du_proportions.csv`? One issue may be when a certain housing type is all 0 for every bzone (like all 0 for general quarters, GQ, used in [AssignLocTypes](https://github.com/VisionEval/VisionEval-Dev/blob/e800e69a6a691fece775d008225cc047bbc81956/docs/tutorials/verspm/Modules_and_Outputs.md#assignloctypes), that may produce this unexpected behavior.

Also, look at `bzone_dwelling_units.csv`, used by [PredictHousing](https://github.com/VisionEval/VisionEval-Dev/blob/e800e69a6a691fece775d008225cc047bbc81956/docs/tutorials/verspm/Modules_and_Outputs.md#predicthousing).

**Comment by shichenfan** [comment]
@dsrosenthal5 @dflynn-volpe   I got same error when I have all GQDU with 0 value in bzone_dwelling_units.csv. So I set all GQDU value equal to 1, and updated the azone_gq_pop_by_age.csv with assumption that every group quarter dwelling have 1 person age in 20 to 29. Then the model could run successfully. I think it's OK for leaving 0 value in bzone_urban-town_du_proportions.csv.

**Comment by dflynn-volpe** [comment]
Great, thanks for clarifying -- @dsrosenthal5, please let us know if a manual modification to `bzone_dwelling_units.csv` solves the problem; we will also make sure to solve it in the code as well.

**Comment by dsrosenthal5** [comment]
@dflynn-volpe @shichenfan thanks! I believe this will resolve the issue, I haven't had a chance to confirm but I do have 0 GQ dwelling units. I will edit later today or tomorrow.

**Comment by dsrosenthal5** [comment]
@dflynn-volpe @shichenfan  Worked!
