### ISSUE TITLE
Can't set NA value for the UzaNameLookup field of the marea_base_year_dvmt.csv file

### ISSUE THREAD

**Issue by shichenfan** [VisionEval/VisionEval-Dev#40]
In VETravelPerformance Package / Initialize Module, NA can't be set  for UzaNameLookup field of the marea_base_year_dvmt.csv file. 
If I provided value for both UrbanLdvDvmt and UrbanHvyTrkDvmt, also with a name of urbanized area for UzaNameLookup, the model seems would still using base year DVMT value from default lookup table instead of UrbanLdvDvmt and UrbanHvyTrkDvmt value I set.

**Comment by dflynn-volpe** [comment]
Are you setting an NA value in UZA Name because the whole study area is urbanized? Looking at the [Initialize documentation](https://github.com/VisionEval/VisionEval-Dev/blob/7118ec6ca3d51d18301fa339008c0b97bfa67000/docs/tutorials/verspm/Modules_and_Outputs.md/#initialize-vetravelperformance) for VETravelPerformance, it should be the urbanized area within the region. I'm also looking at documentation in the [VE-RSPM training](https://github.com/VisionEval/VisionEval-Dev/blob/development/api/VE_Training_March_13-14_2019/VE_Training.md#user-inputs-30), which does indicate that this can be blank.

However, a note in the documentation of the [Initialize module](https://github.com/VisionEval/VisionEval-Dev/blob/development/sources/modules/VETravelPerformance/R/Initialize.R) does indicate that `The UzaNameLookup must be specified in the 'marea_base_year_dvmt.csv' for any marea for which complete data are not specified.` 

Can you clarify what you are trying to do so we can help figure out a solution?

**Comment by shichenfan** [comment]
@dflynn-volpe  Thank you for pointing out the document, I will check it.

I'm trying to set UrbanLdvDvmt and UrbanHvyTrkDvmt by my own input values instead of using default data from the look-up table.

From my understanding, there are two options for setting the 'marea_base_year_dvmt.csv'. One is set the Uza name and the model will use the DVMT of light-duty vehicle and truck from its default database. Another one is that the user provides DVMT of LDV and truck as variables UrbanLdvDvmt and UrbanHvyTrkDvmt, so the Uza name could be blank.  Please correct me if I’m wrong on that. I wanted to try both ways and compare the results.

**Comment by dsrosenthal5** [comment]
@shichenfan @dflynn-volpe  I have also run into this issue. Albany, OR is not included in the Uza table and I was using Corvallis, OR as a substitute. Now I have local DVMT values that I would like to use. I've substituted values into the 'marea_base_year_dvmt', 'marea_dvmt_split_by_road_class', 'region_base_year_dvmt', and 'region_base_year_hvytrk_dvmt' files. 

If I use 'NA' for the UzaLookup value the model fails to initialize but I can get it to start by using ' ' in the Uza field. Ultimately it stops in the 'CalculateRoadPerformance' module and outputs this:
![image](https://user-images.githubusercontent.com/48492597/60052381-f1a02100-9689-11e9-8dd5-2b12879b3616.png)

**Comment by arashasadabadi** [comment]
@dsrosenthal5 @shichenfan I revised the "marea_base_year_dvmt.csv" with putting some numbers for DVMT columns and then change the "UzaNameLookup" to something arbitrary, for instance use "A" . Then I changed "marea_dvmt_split_by_road_class.csv" accordingly and I was able to run the model successfully with my changes to DVMT were applied to results. Note that right now the setting of "UzaNameLookup" is a in a way that prohibits "NA" values . We can change it for future to accept NA values as well. 


@dflynn-volpe The documents of the module doesn't look right. It seems that there is not a systematic way proposing how the user can input the desired values for DVMT.

**Comment by arashasadabadi** [comment]
@dsrosenthal5 The problem with your run is completely input specisifc. The values of (0.64 | 0.19749 | 0.162509) for light-duty vechiles split is problematic! The reason behind this is little complex and need more investgiations. There is a VE funrion "binarySearch" which is not working with these values. I will try to see if I can fix this.

**Comment by arashasadabadi** [comment]
@dsrosenthal5 Which MPO does this split of road class data ( 0.64, 0.19, 0.16) belong to?

**Comment by dsrosenthal5** [comment]
@arashasadabadi Those values belong to the Albany Area MPO for Albany, OR. Is it the high percentage of interstate DVMT? If some of the values are out of a range that works for the module I'm sure I could make some reasonable assumptions within the constraints for values that work.

**Comment by arashasadabadi** [comment]
@dsrosenthal5 Yes, The ratio of interstate VMT to arterial VMT is big. The model has a module to calibrate the calculated road class shares based on the user defined splits in input file. Because of the difference in those values the algorithm doesn't work. I don't think we should change the inputs as long as they are valid. I have to rebuild the algorithm in the model

**Comment by arashasadabadi** [comment]
@dsrosenthal5 I changed a module in VETravelPerfomance package to fix this. The model is now running for me with the dvmt road class split shares calibrated bases on your split share input without any error. I sent a pull request to the visioneval_dev development branch. You can either pull the latest version from visioneval_dev once the pull_request passes the checks and get accepted, or if you want to do it faster just manually see the commit in pull request( it's basically a change in numbers in the script) and manually update the CalculateRoadPerformance.R script in the VETravelPerfomance package on your machine an re-install it.

**Comment by dsrosenthal5** [comment]
@arashasadabadi thanks for you help! worked!
