### ISSUE TITLE
AssignDrivers Module requires some Urban DU prop <1

### ISSUE THREAD

**Issue by dsrosenthal5** [VisionEval/VisionEval-Dev#41]
With all my bzone PropUrbanSFDU to equal 1 in the "bzone_urban-town_du_proportions" input the model was crashing in the "AssignDrivers" module. When I changed some of them to values less than 1 the model ran through. It seems like the module requires some rural households to run the driver assignment so at least one of the Bzones should have an Urban DU Prop <1.

There are probably at least some rural areas in most applications but I could see future scenarios where we may want to test a completely urbanized region.

**Comment by dflynn-volpe** [comment]
Interesting -- we can look into this and clarify [in the documentation](https://github.com/VisionEval/VisionEval-Dev/blob/e800e69a6a691fece775d008225cc047bbc81956/docs/tutorials/verspm/Modules_and_Outputs.md#user-input-files-6) that ProbUrbanSFDU must be < 1. We should look into making it flexible to accomodate complete urban applications.

**Comment by arashasadabadi** [comment]
I found the source of this problem. All of the following modules has non-Metro models which applies to the households who reside in non-Urban areas. 
AssignDrivers
AssignVehicleOwnership
CalculateAltModeTrips
CalculateVehicleTrips
In the case  @dsrosenthal5 mentioned (where all the households are located in Urban area) model crashes because it cannot find a single household to apply the non Metro function . As a short term solution I revised the scripts by adding a condition where it makes sure the non metro model only applies when we have at least on household locates in non-Urban areas. @dflynn-volpe do you want me to commit those changes?

**Comment by jrawbits** [comment]
@arashasadabadi Can you make a pull request against the development branch with these changes? My main concern with what you're describing is that we might get some downstream failure if the non-metro model is not run...

**Comment by arashasadabadi** [comment]
@jrawbits I will make a pull request against the development branches. I tested the model through the end and it was successful. Ideally it should not make any problem because every household gets the model value through the metro model ( considering they are located in urban area)

**Comment by jrawbits** [comment]
I'm closing this, though it may resurface.
