### ISSUE TITLE
Support Updating/Replacing Package Data without rebuilding package

### ISSUE THREAD

**Issue by jrawbits** [VisionEval/VisionEval-Dev#52]
It is desirable to allow VisionEval users to re-estimate model parameters from updated or alternative data sources.

Architecturally, that could be supported by separating the data sets from the model run code.  The goal would be allow the user, without rebuilding any of the packages, to develop/estimate their own versions of any or all of the datasets and seamlessly use those during the model runs.

Consider splitting the packages in two (at least logically), so there is

1. a “model run” package (which would include the VE module functions that are called by VERSPM etc) and
2. a “data package” which includes
    a.	the estimation code (which will build the default data sets when the package is built, but which is also available to a user to rebuild any of the data sets from their own data)
    b.	the already estimated default data sets
    c.	some new code that puts a level of indirection between the request for data from the module run function and delivery of the data (so rather than just loading the data from the package, it will check against a user-configurable table to determine whether to use a specific data set from the user’s file system in place of the default).

At a minimum, we could serve the purpose initially by
(a)	implementing (2)c, the indirection, and then
(b)	adding (2)a which would allow the user to install the packages and then use functions within them to (re)build the datasets in their local file system (and construct the redirection table so the right data is used when a model is run).

Feel free to discuss this suggestion in comments

**Comment by jrawbits** [comment]
Another bad side-effect: all the contents of the "data" folder also end up in the binary package "R" directory because they are re-created during the binary build.  We badly need to re-architect the model estimation elements (that build the "data" folder) so those are not part of building the runtime package!

**Comment by gregorbj** [comment]
The items in the data folder are not residues. They are the data objects used in implementing and documenting a model:
1) the module specifications list, 
2) objects that are used by the module function to implement a model such as the HtProb_HtAp matrix dataset which contains household type probabilities by household type and person age (VESimHouseholds)
3) objects used to document a model. 

I would argue against moving these outside of the package that implements the module because it will add complexity to the system and increased difficulty for understanding a module.

I do think, however, there are ways to trim down the size of the data. One of the problems is that a module model estimation follows the convention of creating and saving a model object, such as produced by lm(), and using predict() to implement the model, a lot of unnecessary data is saved because functions like lm() include all the model estimation data in the object. That is one of the reasons why I developed functions for implementing linear models and binomial logit models which don't use predict(). My code only saves the model formula and a few other parameters. Where I have used other models that use predict() like the ordered logit model for car ownership, I have stripped out as much of the extraneous data as I could and still enable predict() to work.

I think the other reason why some of the R data files are so large is that if they are functions or contain functions, R saves the environments in which the functions are defined. For example, in the VESimHouseholds package, the HHIncModel_ls.rda file is 3.487 MB even though the object size is only a bit over 25,440 bytes. However when the object is loaded, the memory size increases by 27.68 MB. 

So I guess there are residues in the form of unneeded data produced by functions like lm() and unneeded objects in environments saved with functions. My preference would be to develop methods for stripping away unneeded data and function environments before they are saved. Moving the data objects to different packages won't solve the problem of large packages and it will make the open science approach more obscure.

**Comment by jrawbits** [comment]
Re the residues: some of the modules are building datasets into the /data folder, but they are not deleting the objects that were built so we get a second copy in the compiled R code for the package. That is probably easy to fix.

There are a couple of use cases implicated by this issue:

1. Users would like to re-estimate parts of some of the models (or provide alternate "default" datasets) using local data.  We would like them to be able to do that without having to do a full VisionEval "build from source". There need to be functions to support that (including re-estimating the models/parameters from different data, and pointing the VisionEval module at the re-estimated information). I'm agnostic with respect to how we package those mechanisms for delivery (I'd be fine with a "data re-estimation interface" and a "run module interface")

2. The current data estimation build approach works badly (and not just because of the "residuals").  The problem is that there are two steps to building the estimated data sets in /data.  The first step is to run R scripts on the raw external data (using inst/extdata) and to generate the datasets that go into /data. The second step is to build what is in /data into the final R package.  The trouble, from a build automation perspective, is that you can't make changes to inst/extdata and the directly build an R package, because /data is loaded FIRST, before the estimating R scripts are run.  So we have to go through the package build process multiple times (more than two, because the package also gets built whenever we do the R CMD check process, and when we build a binary version for Windows).  What we need is a two-step process: (a) Run R scripts ahead of the R package build process to turn inst/extdata (or data-raw) into R data sets in the /data folder; and (b) build the package, running a smaller set of R scripts to create the module functions and interfaces.

I will argue that the second use case (for someone who is not planning to re-estimate the models) does not require any of the raw data to be placed into the R package (so we should use the data-raw approach, not the inst/exdata approach).  Anyone who needs the source can just pull the Github and build/re-build it with VE-Installer.  The "extra" called for in the first use case is to allow a specific API for "data/parameter re-estimation/substitution) that does not require pulling the Github and rebuilding all the datasets at that level.

What I want ultimately is to package the system in ways that are targeted to specific types of user needs, so people do not have to torment themselves learning to install stuff that they'll never need or use.

**Comment by gregorbj** [comment]
I'm still not seeing the problem aside from residual data which can be addressed. 

There are only 2 packages that users would customize to estimate models that match their region conditions: VESimHouseholds and VEFuelsAndPowertrains. The process does require more R knowledge than simply running a VE model, but is much much simpler than what users have to deal with when customizing an urban travel demand model for their area (where a consultant or highly technically proficient staff run alogit or other software to estimate model and then write custom software to implement). To create a customized VESimHouseholds package for their region the user
1) Downloads the source package from the repository
2) Reads the documentation
3) Changes the files in the inst/extdata directory according to the documentation using their regional data
4) Starts RStudio 
5) Rebuilds the package
6) Replaces the default package with the new package

The framework allows the user to have a different name to distinguish their customized package from the default package. For example a VESimHouseholds package for Atlanta could be named VESimHouseholdsAtlanta. Then the user would substitute that name in the RunModel.R script accordingly and specify that package in the RequiredVEPackages listing in the run_parameters.json file.

Similarly, customized VEPowertrainsAndFuels packages can be developed to characterize different powertrains and fuels futures (e.g. California ZEV vs. BAU). There are a few examples in the gregorbj/OregonDOT-VisionEval repo. The hard part of creating these was getting the csv files together with the data to represent different scenarios. After that, it was easy to run RStudio to build the packages.

**Comment by jrawbits** [comment]
Steps 5 and 6 require building the package two times: once to move inst/extdata into R data sets in data, and once to build what is in data along with the function definitions in the package.  That makes automated building a mess of redundant time-consuming operations.

From a product delivery standpoint, manual construction of packages is a non-starter.  We need to engineer a build process that is efficient and complete (i.e. enabling a rapid rebuild of individual packages where only what has changed is rebuilt, and also enabling a complete end-to-end run of tests prior to committing to Github).

We're not going to do anything about this issue in the short term, and I appreciate your comments about the current expected workflow.  The bottom line, however, is that the R scripts used to build the estimated model datasets should be run separately from the R package build process (because otherwise changes can be made to the raw datasets that do not appear in the package data folder). Given that they need to run separately, I think it would make sense to allow them to be detached from building the package (i.e. treating what does into the data folder as "defaults", and allowing users to run the separate estimation R code on their own data to use different versions). For the time being, doing that requires setting up the VE-Installer build process, which is not hard but is overkill for someone whose only interest is in locally estimating certain modules.

You've given me food for thought (as always) so I'll be looking at alternate approaches to streamlining and bullet-proofing the process.
