### ISSUE TITLE
CSV of scenarioviewer data

### ISSUE THREAD

**Issue by mrspeel** [VisionEval/VisionEval-Dev#65]
Can a CSV file be created of the data displayed in the scenarioviewer? Perhaps automatically created in /outputs/ folder when the multirun model runs are competed.
ie. one row for each scenario, one column for each viewer output distribution metric.

**Comment by gregorbj** [comment]
Since the scenario viewer runs in a webpage, the HTML/Javascript standards prohibit web apps from saving files. This is important for security purposes, otherwise malicious web apps could do a lot more harm than they otherwise would do. What the user can do is just highlight and copy the cells in the filtered table and then paste into a spreadsheet. Longer term, to implement a saving mechanism I can think of the following options:
1) Implement the viewer as a web service to which the user uploads their scenario data, uses the viewer interface, and then downloads the filtered scenario data.
2) Implement the viewer as a native application that doesn't run through the web browser. There are several options for doing this such as building as a Shiny application, Electron application, React Native application, or Flutter application.

**Comment by jrawbits** [comment]
The goal is not to have the scenario viewer application save the data, but rather to generate it in parallel the JSON parts of the Scenario Viewer (so in addition to dumping a JSON file with the data for the viewer, it dumps a .csv file with the raw data). That should be pretty painless.

In the medium-to-long term, I'd like to develop a layered architecture for accessing data so that it is easy for someone to drop the results into a new output format.  I'd also like to revisit the HTML viewer with the intent of making it easier for a user to customize for their own purposes.

**Comment by dflynn-volpe** [comment]
Simple solution closed by PR #77
