### ISSUE TITLE
Azone input file order dependence

### ISSUE THREAD

**Issue by mrspeel** [VisionEval/VisionEval-Dev#73]
A bug was found that Azone input entries (rows) must always be in the same order.  @gregorbj found this in debugging VE-State.  For now we have just forced all the inputs to be in a consistent order, since we couldn't quickly identify the bug.  This should be corrected ASAP as likely others will not know to do this.

**Comment by gregorbj** [comment]
Found the bug. It resides in the processModuleInputs function. This function takes a list of module specifications, sorts by file and then goes through each file and checks and otherwise processes the inputs in that file. The data are put into the standard datastore interchange list structure (named ProcessedInputs_ls in the initializeModel function). The standard list structure organizes data by table. This list is then passed to the inputsToDatastore function which puts the processed inputs into the datastore in the proper geographic order.

The bug occurs because the data from several input files may be combined in the same table component in the list and there is no checking that the data in the several files is ordered in the same way. When each file is processed, the geography units (e.g. Azone) are saved in the list. In other words, if there is more than one file (e.g. Azone input file) the geography entries get overwritten with each subsequent file processed.

Later, the inputsToDatastore sorts the data in the list in the proper order in the datastore, but by that time, the damage has been done.

This will be easy to fix. I'll make a fix and submit a pull request shortly.

**Comment by jrawbits** [comment]
Super. Thanks!
