### ISSUE TITLE
Batch install file does not run

### ISSUE THREAD

**Issue by wolanoly** [VisionEval/VisionEval-Dev#78]
Hello,

I have downloaded the latest version of R (3.6.1) and RStudio. I have also downloaded the VE-installer folder. I opened it and clicked on the Batch icon to download it as the Vision Eval webpage recommends. It does not download it, but instead opens up this webpage: https://cran.r-project.org/bin/windows/base/old/

Seeing that the this file did not work, I decided to instead use the Vision Eval R file to download it. I open that file in RStudio and run the script but the install does not work. I am told "there is no package called 'visioneval'.

**Comment by dflynn-volpe** [comment]
Thanks for your interest in VisionEval! 
Did you download the installer .zip file from the [download page](https://visioneval.org/category/download.html) on the website? We are working to make sure there is clarity on the best way to get VisionEval working, and the goal is for the [visioneval.org](https://visioneval.org/) website to be the primary starting point for users. Since you have R 3.6.1, you should download the corresponding version of the VisionEval installer ([here](https://github.com/VisionEval/VisionEval/releases/download/v1.0.1/VE-installer-Windows-R3.6.1.2019-09-18.zip)). 

If that's still a problem, we can work to figure out what's going on. Thanks for bringing this issue to our attention.

**Comment by wolanoly** [comment]
Hi dflynn. Thanks for the help. I actually just got it to work! The key was putting R, Rstudio and my VE files in the same directory.

**Comment by dflynn-volpe** [comment]
Glad that worked for you! Technically there should be no need to have the R and RStudio applications in the same location as the VisionEval code, but as long as it works for you to try out the code, all good. 

Please feel free to open a new issue if anything else comes up. I'll close this issue now.
